# Path to the simc executable
# If you have spaces in your path, create an environment variable (e.g. SIMC_PATH),
# then set it to '%SIMC_PATH%' (including the single quotes).
SimcPath: D:\Dev\SimulationCraft

# How many threads to use
Threads: 3

###
### You can most likely leave the following the way they are.
###

# Where tool-wide config files are stored
ConfigFolder: conf

# Where reports / CSV files will be saved
ReportsFolder: reports

# Where simc log files will be saved
LogsFolder: logs

# Where generated simc files will be saved
GeneratedFolder: generated

# Where templates for the scripts are placed
ProfilesFolder: profiles
